services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/sql/ini:/docker-entrypoint-initdb.d

  mongo:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=123123
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.authc.apiKey.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=kibana_system
#      - ELASTICSEARCH_PASSWORD=VvJlR2DZPz0DBli*G2jk
    ports:
      - "5601:5601"

  consul:
    image: "hashicorp/consul:latest"
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - consul-data:/consul/data

  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./deploy/config/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./deploy/config/promtail.yml:/etc/promtail/config.yml
      - ./app/gateway/log:/logs/gateway
      - ./app/cart/log:/logs/cart
      - ./app/checkout/log:/logs/checkout
      - ./app/email/log:/logs/email
      - ./app/order/log:/logs/order
      - ./app/payment/log:/logs/payment
      - ./app/product/log:/logs/product
      - ./app/user/log:/logs/user
    command: -config.file=/etc/promtail/config.yml

volumes:
  mysql-data:
  mongo-data:
  redis-data:
  es-data:
  rabbitmq-data:
  consul-data:
  grafana-data:
