all:
	#make dashboard
	make -C consul make
	make -C minio make
	make -C mongodb make
	make -C mysql make
	make -C rabbitmq make
	make -C redis make
	make -C loki make
	make -C es make
	make -C kibana make
	make -C prometheus make
	make -C jaeger make

